version: '3.8'

services:
  loadbalancer:
    build:
      context: ./Payroc.App
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - lb-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  backend1:
    build:
      context: ./BackendServer
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - SERVER_ID=Backend-1
    networks:
      - lb-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  backend2:
    build:
      context: ./BackendServer
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - SERVER_ID=Backend-2
    networks:
      - lb-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  backend3:
    build:
      context: ./BackendServer
      dockerfile: Dockerfile
    environment:
      - PORT=80
      - SERVER_ID=Backend-3
    networks:
      - lb-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  lb-network:
    driver: bridge